# Generated by Django 5.2 on 2026-08-09 18:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('PUSH', 'Push'), ('SMS', 'SMS')], max_length=8)),
                ('event', models.CharField(choices=[('VISIT_EARNED', 'Начислено посещение'), ('CASHBACK_EARNED', 'Начислен cashback'), ('GIFT_EARNED', 'Получен подарок'), ('REDEMPTION_REQUESTED', 'Запрос подтверждения списания'), ('REDEMPTION_CONFIRMED', 'Списание подтверждено'), ('REDEMPTION_REJECTED', 'Списание отклонено'), ('CASHBACK_EXPIRING', 'Cashback скоро сгорит'), ('CASHBACK_EXPIRED', 'Cashback сгорел'), ('TRANSACTION_REVERSED', 'Операция отменена'), ('SECURITY_ALERT', 'Событие безопасности'), ('OTP', 'Код подтверждения')], db_index=True, max_length=32)),
                ('language', models.CharField(default='ru', max_length=8)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('body', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'В очереди'), ('SENT', 'Отправлено'), ('FAILED', 'Ошибка'), ('SKIPPED', 'Пропущено')], db_index=True, default='QUEUED', max_length=16)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
