# Generated by Django 5.2 on 2026-08-09 18:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_type', models.CharField(choices=[('USER', 'Пользователь'), ('ADMIN', 'Администратор организации'), ('DIRECTOR', 'Директор AlaSoft'), ('SYSTEM', 'Система')], max_length=16)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('key', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'idempotency_records',
                'indexes': [models.Index(fields=['created_at'], name='idempotency_created_3fb3ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('actor_type', 'actor_id', 'key'), name='uniq_idempotency_actor_key')],
            },
        ),
    ]
