# Generated by Django 5.2 on 2026-08-09 18:13

import apps.users.managers
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('USER', 'Пользователь'), ('ORGANIZATION_ADMIN', 'Администратор организации'), ('DIRECTOR', 'Директор AlaSoft')], db_index=True, default='USER', max_length=32)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('ky', 'Кыргызча')], default='ru', max_length=8)),
                ('public_code', models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True)),
                ('qr_token', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('pin_hash', models.CharField(blank=True, default='', max_length=255)),
                ('pin_updated_at', models.DateTimeField(blank=True, null=True)),
                ('failed_pin_attempts', models.PositiveSmallIntegerField(default=0)),
                ('pin_locked_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_registration_complete', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('purpose', models.CharField(choices=[('REGISTER', 'Регистрация'), ('LOGIN', 'Вход'), ('PIN_RESET', 'Сброс PIN')], max_length=16)),
                ('code_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('VERIFIED', 'Подтверждён'), ('CONSUMED', 'Использован'), ('EXPIRED', 'Истёк'), ('FAILED', 'Исчерпаны попытки')], db_index=True, default='PENDING', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('verification_expires_at', models.DateTimeField(blank=True, null=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'otp_challenges',
                'indexes': [models.Index(fields=['phone', 'purpose', 'status'], name='otp_challen_phone_615d81_idx'), models.Index(fields=['expires_at'], name='otp_challen_expires_ec0c81_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=128)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], default='android', max_length=16)),
                ('device_name', models.CharField(blank=True, default='', max_length=128)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('fcm_token', models.CharField(blank=True, default='', max_length=512)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('ky', 'Кыргызча')], default='ru', max_length=8)),
                ('refresh_jti', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('is_trusted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_devices',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_role_a8f2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='users_date_jo_0c802f_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'is_active'], name='user_device_user_id_14e9e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='userdevice',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='uniq_user_device'),
        ),
    ]
