# Generated by Django 5.2 on 2026-08-09 18:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_amount', models.BigIntegerField()),
                ('remaining_amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Активен'), ('SPENT', 'Израсходован'), ('EXPIRED', 'Сгорел'), ('CANCELLED', 'Аннулирован')], db_index=True, default='ACTIVE', max_length=16)),
                ('earned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Начисление cashback',
                'verbose_name_plural': 'Начисления cashback',
                'db_table': 'cashback_lots',
                'ordering': ['expires_at', 'earned_at'],
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Доступен'), ('PENDING_REDEMPTION', 'Ожидает подтверждения'), ('USED', 'Использован'), ('CANCELLED', 'Аннулирован')], db_index=True, default='AVAILABLE', max_length=24)),
                ('title_ru', models.CharField(blank=True, default='Подарок', max_length=150)),
                ('title_ky', models.CharField(blank=True, default='Белек', max_length=150)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Подарок',
                'verbose_name_plural': 'Подарки',
                'db_table': 'gifts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('GIFT', 'Подарок'), ('CASHBACK', 'Cashback')], max_length=16)),
                ('purchase_total', models.BigIntegerField(blank=True, null=True)),
                ('spend_amount', models.BigIntegerField(blank=True, null=True)),
                ('cash_paid', models.BigIntegerField(blank=True, null=True)),
                ('earn_amount', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('CONFIRMED', 'Подтверждено'), ('REJECTED', 'Отклонено'), ('EXPIRED', 'Истекло'), ('CANCELLED', 'Отменено')], db_index=True, default='PENDING', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('result_transactions', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Запрос на списание',
                'verbose_name_plural': 'Запросы на списание',
                'db_table': 'redemption_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('USER', 'Пользователь'), ('ADMIN', 'Администратор организации'), ('DIRECTOR', 'Директор AlaSoft'), ('SYSTEM', 'Система')], max_length=16)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('type', models.CharField(choices=[('VISIT_EARN', 'Начислено посещение'), ('GIFT_CREATED', 'Получен подарок'), ('GIFT_REDEEM', 'Подарок использован'), ('CASHBACK_EARN', 'Начислен cashback'), ('CASHBACK_SPEND', 'Списан cashback'), ('CASHBACK_EXPIRE', 'Cashback сгорел'), ('REVERSAL', 'Операция отменена')], db_index=True, max_length=24)),
                ('amount', models.BigIntegerField(blank=True, help_text='Тыйын; NULL для VISIT/GIFT', null=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Выполнена'), ('REVERSED', 'Отменена'), ('PENDING', 'Ожидает'), ('FAILED', 'Ошибка')], db_index=True, default='COMPLETED', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'transactions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserOrganizationState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_progress', models.PositiveIntegerField(default=0)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('available_gifts', models.PositiveIntegerField(default=0)),
                ('total_gifts_earned', models.PositiveIntegerField(default=0)),
                ('total_gifts_used', models.PositiveIntegerField(default=0)),
                ('cashback_available', models.BigIntegerField(default=0)),
                ('cashback_total_earned', models.BigIntegerField(default=0)),
                ('cashback_total_spent', models.BigIntegerField(default=0)),
                ('cashback_total_expired', models.BigIntegerField(default=0)),
                ('first_activity_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Состояние клиента в организации',
                'verbose_name_plural': 'Состояния клиентов в организациях',
                'db_table': 'user_organization_states',
            },
        ),
    ]
