# Generated by Django 5.2 on 2026-08-09 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loyalty', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbacklot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashback_lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gift',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gifts', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='gift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redemption_requests', to='loyalty.gift'),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemption_requests', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemption_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_transactions', to='loyalty.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gift',
            name='redeem_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redeemed_gifts', to='loyalty.transaction'),
        ),
        migrations.AddField(
            model_name='gift',
            name='source_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_gifts', to='loyalty.transaction'),
        ),
        migrations.AddField(
            model_name='cashbacklot',
            name='source_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashback_lots', to='loyalty.transaction'),
        ),
        migrations.AddField(
            model_name='userorganizationstate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='userorganizationstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='redemptionrequest',
            index=models.Index(fields=['user', 'status', '-created_at'], name='redemption__user_id_3482d2_idx'),
        ),
        migrations.AddIndex(
            model_name='redemptionrequest',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='redemption__organiz_7850ab_idx'),
        ),
        migrations.AddIndex(
            model_name='redemptionrequest',
            index=models.Index(fields=['status', 'expires_at'], name='redemption__status_e82a33_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='transaction_user_id_ced08a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['organization', '-created_at'], name='transaction_organiz_49b9de_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'organization', '-created_at'], name='transaction_user_id_346bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', '-created_at'], name='transaction_type_c28faa_idx'),
        ),
        migrations.AddIndex(
            model_name='gift',
            index=models.Index(fields=['user', 'organization', 'status'], name='gifts_user_id_662088_idx'),
        ),
        migrations.AddIndex(
            model_name='gift',
            index=models.Index(fields=['organization', 'status'], name='gifts_organiz_0f4948_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbacklot',
            index=models.Index(fields=['user', 'organization', 'expires_at', 'remaining_amount'], name='idx_lot_fifo'),
        ),
        migrations.AddIndex(
            model_name='cashbacklot',
            index=models.Index(fields=['status', 'expires_at'], name='idx_lot_expiry_scan'),
        ),
        migrations.AddConstraint(
            model_name='cashbacklot',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_amount__gte', 0)), name='cashback_lot_remaining_non_negative'),
        ),
        migrations.AddIndex(
            model_name='userorganizationstate',
            index=models.Index(fields=['organization', 'last_activity_at'], name='user_organi_organiz_60f4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='userorganizationstate',
            index=models.Index(fields=['user', 'last_activity_at'], name='user_organi_user_id_4eb27a_idx'),
        ),
        migrations.AddConstraint(
            model_name='userorganizationstate',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='uniq_user_org_state'),
        ),
    ]
