[pytest]
DJANGO_SETTINGS_MODULE = core.settings.test
python_files = test_*.py
testpaths = apps
; --ds перекрывает DJANGO_SETTINGS_MODULE из окружения контейнера
addopts = -q --disable-warnings --ds=core.settings.test
