# Generated by Django 5.2 on 2026-08-09 18:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('USER', 'Пользователь'), ('ADMIN', 'Администратор организации'), ('DIRECTOR', 'Директор AlaSoft'), ('SYSTEM', 'Система')], max_length=16)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_phone', models.CharField(blank=True, default='', max_length=20)),
                ('action', models.CharField(choices=[('LOGIN', 'Вход'), ('LOGIN_FAILED', 'Неудачный вход'), ('LOGOUT', 'Выход'), ('PIN_SET', 'Установлен PIN'), ('PIN_RESET', 'Сброшен PIN'), ('ORGANIZATION_CREATED', 'Организация создана'), ('ORGANIZATION_UPDATED', 'Организация изменена'), ('ORGANIZATION_BLOCKED', 'Организация заблокирована'), ('ORGANIZATION_UNBLOCKED', 'Организация разблокирована'), ('PROGRAM_UPDATED', 'Настройки программы изменены'), ('ADMIN_CREATED', 'Создан администратор'), ('ADMIN_RESET', 'Сброшен доступ администратора'), ('VISIT_EARNED', 'Начислено посещение'), ('CASHBACK_EARNED', 'Начислен cashback'), ('CASHBACK_SPENT', 'Списан cashback'), ('GIFT_REDEEMED', 'Использован подарок'), ('REDEMPTION_CREATED', 'Создан запрос на списание'), ('REDEMPTION_CONFIRMED', 'Списание подтверждено'), ('REDEMPTION_REJECTED', 'Списание отклонено'), ('TRANSACTION_REVERSED', 'Транзакция отменена'), ('CASHBACK_EXPIRED', 'Cashback сгорел')], db_index=True, max_length=48)),
                ('entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('entity_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Аудит',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
