# Generated by Django 5.2 on 2026-08-09 18:13

import apps.organizations.validators
import django.core.validators
import django.db.models.deletion
import django_resized.forms
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashback_rate_bps', models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('max_spend_percent_bps', models.PositiveIntegerField(default=3000, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('expiry_days', models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('min_purchase_amount', models.BigIntegerField(default=0, help_text='В тыйынах')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Программа CASHBACK',
                'verbose_name_plural': 'Программы CASHBACK',
                'db_table': 'cashback_programs',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_ky', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
                'ordering': ['sort_order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Администратор организации',
                'verbose_name_plural': 'Администраторы организаций',
                'db_table': 'organization_admins',
            },
        ),
        migrations.CreateModel(
            name='VisitProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_visits', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('reward_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('reward_title_ru', models.CharField(blank=True, default='Подарок', max_length=150)),
                ('reward_title_ky', models.CharField(blank=True, default='Белек', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Программа VISIT',
                'verbose_name_plural': 'Программы VISIT',
                'db_table': 'visit_programs',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=85, scale=None, size=[512, 512], upload_to='organizations/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp']), apps.organizations.validators.validate_logo_size])),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_ky', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('working_hours', models.JSONField(blank=True, default=list)),
                ('loyalty_type', models.CharField(choices=[('VISIT', 'Накопительная (N+1)'), ('CASHBACK', 'Cashback')], max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('BLOCKED', 'Заблокирована')], db_index=True, default='ACTIVE', max_length=16)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organizations.category')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
    ]
