# Generated by Django 5.2 on 2026-08-09 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbackprogram',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashback_program', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationadmin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_org_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationadmin',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitprogram',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit_program', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status', 'loyalty_type'], name='organizatio_status_dc5ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['category', 'status'], name='organizatio_categor_6173eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationadmin',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization',), name='uniq_active_admin_per_org'),
        ),
        migrations.AddConstraint(
            model_name='organizationadmin',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='uniq_active_org_per_admin'),
        ),
    ]
